POST http://localhost:8081/enviar-notificacion
Content-Type: application/json

{
  "destinatario": "Ramiro",
  "medioDeContacto": {
    "tipoMedioContacto": "EMAIL",
    "direccion": "rasilva@frba.utn.edu.ar"
  },
  "mensaje": "Probando 123"
}